name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure PHP
      uses: shivamathur/setup-php@v2
      with: 
        php-version: '8.2'
        tools: composer

    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

